CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL PRIMARY KEY, 
    NAME VARCHAR(100), 
    EMAIL VARCHAR(100), 
    "PASSWORD" VARCHAR(100)
);

CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON USERS (EMAIL);
