server:
    port: 8082

spring:
    application:
        name: notification
    rabbitmq:
            addresses: amqps://vycflmbf:VESS6iKwi69C88OGQAJYFDT2_0j9CYaf@beaver.rmq.cloudamqp.com/vycflmbf
            queue:
                default.email

    mail:
        host: smtp.gmail.com
        port: 587
        username: <email>
        password: <password>
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    data:
        mongodb:
            host: localhost
            username: admin
            password: 123
            port: 27018
            database: notification

