version: '3.8'

services:
  user_db:
    container_name: ms-user
    image: postgres
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ms-user
  email_db:
    container_name: ms-email
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ms-email