server:
    port: 8081

spring:
    application:
        name: fraud
    data:
        mongodb:
            host: localhost
            username: admin
            password: 123
            port: 27017
            database: frauds
eureka:
    client:   
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: true    