spring:
    application:
        name: orders_ms
    data:
        mongodb:
            authentication-database: admin
            auto-index-creation: true
            host: localhost
            port: 27017
            database: btgpactualdb
            username: admin
            password: password
