services:
  mongodb:
    container_name: database
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password



  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    ports:
      - 15672:15672
      - 5672:5672
 