services:
  mysql:
    container_name: "notifications"
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=notifications_db'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=admin123'
      - 'MYSQL_USER=admin'
    ports:
      - '3307:3306'